"""
Données pré-calculées de la ligue MPP — généré le 2026-07-20 16:59.
Ne pas éditer à la main : régénérer avec `python3 fetch_data.py`.
"""

GENERATED_AT = "2026-07-20 16:59"

LEAGUE_NAME = "Coupe du Mao (à mao)"

# (pseudo, prénom, rang MPP, points MPP)
LEAGUE = [
    ('Adedadz', 'Adélaïde', 1, 4811),
    ('AlexRougier', 'Alexandre', 2, 4629),
    ('Sir_Chatonne', 'Alexandre', 3, 4329),
    ('K-Dab', 'Karim', 4, 4324),
    ('M9rgan', 'Morgan', 5, 4079),
    ('GOAT#UEBF1WEA', 'Gilian', 6, 3922),
    ('Foz', 'Clément', 7, 3920),
    ('CedreLePoulpe', 'Cedric', 8, 3805),
    ('Merwi', 'Marie', 9, 3713),
    ('Jean-Porc-Jajo', 'Jade', 10, 3711),
    ('HugBagr', 'Hug', 11, 3650),
    ('BRANDAO_DOBRAZIL', 'Samba', 12, 3394),
    ('Pascalou_', 'Thomas', 13, 1556),
]

# {bookmaker: {pseudo: {profit, roi, wins, bets, ...}}}
# Toutes les valeurs sont pour une mise de 1€ (linéaire, on multiplie à l'affichage).
DATA = {
    'best': {
        'Adedadz': {
            'profit': 10.1,
            'roi': 9.71,
            'wins': 69,
            'bets': 104,
            'winRate': 66.3,
            'totalStake': 104,
            'averageOdd': 1.65,
            'bestWinStreak': 7,
        },
        'AlexRougier': {
            'profit': 12.69,
            'roi': 12.2,
            'wins': 66,
            'bets': 104,
            'winRate': 63.5,
            'totalStake': 104,
            'averageOdd': 1.77,
            'bestWinStreak': 11,
        },
        'Sir_Chatonne': {
            'profit': 5.44,
            'roi': 5.39,
            'wins': 65,
            'bets': 101,
            'winRate': 64.4,
            'totalStake': 101,
            'averageOdd': 1.64,
            'bestWinStreak': 6,
        },
        'K-Dab': {
            'profit': 9.83,
            'roi': 9.45,
            'wins': 62,
            'bets': 104,
            'winRate': 59.6,
            'totalStake': 104,
            'averageOdd': 1.84,
            'bestWinStreak': 6,
        },
        'M9rgan': {
            'profit': 1.39,
            'roi': 1.34,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.82,
            'bestWinStreak': 6,
        },
        'GOAT#UEBF1WEA': {
            'profit': -6.71,
            'roi': -6.45,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.68,
            'bestWinStreak': 6,
        },
        'Foz': {
            'profit': 15.96,
            'roi': 16.8,
            'wins': 56,
            'bets': 95,
            'winRate': 58.9,
            'totalStake': 95,
            'averageOdd': 1.98,
            'bestWinStreak': 6,
        },
        'CedreLePoulpe': {
            'profit': -6.17,
            'roi': -5.99,
            'wins': 58,
            'bets': 103,
            'winRate': 56.3,
            'totalStake': 103,
            'averageOdd': 1.67,
            'bestWinStreak': 6,
        },
        'Merwi': {
            'profit': -5.94,
            'roi': -5.71,
            'wins': 59,
            'bets': 104,
            'winRate': 56.7,
            'totalStake': 104,
            'averageOdd': 1.66,
            'bestWinStreak': 5,
        },
        'Jean-Porc-Jajo': {
            'profit': 10.29,
            'roi': 10.95,
            'wins': 50,
            'bets': 94,
            'winRate': 53.2,
            'totalStake': 94,
            'averageOdd': 2.09,
            'bestWinStreak': 6,
        },
        'HugBagr': {
            'profit': -11.17,
            'roi': -10.74,
            'wins': 52,
            'bets': 104,
            'winRate': 50,
            'totalStake': 104,
            'averageOdd': 1.79,
            'bestWinStreak': 4,
        },
        'BRANDAO_DOBRAZIL': {
            'profit': 5.56,
            'roi': 6.25,
            'wins': 53,
            'bets': 89,
            'winRate': 59.6,
            'totalStake': 89,
            'averageOdd': 1.78,
            'bestWinStreak': 6,
        },
        'Pascalou_': {
            'profit': -27.84,
            'roi': -34.37,
            'wins': 14,
            'bets': 81,
            'winRate': 17.3,
            'totalStake': 81,
            'averageOdd': 3.8,
            'bestWinStreak': 2,
        },
    },
    'betclic': {
        'Adedadz': {
            'profit': 8.77,
            'roi': 8.43,
            'wins': 69,
            'bets': 104,
            'winRate': 66.3,
            'totalStake': 104,
            'averageOdd': 1.63,
            'bestWinStreak': 7,
        },
        'AlexRougier': {
            'profit': 10.82,
            'roi': 10.4,
            'wins': 66,
            'bets': 104,
            'winRate': 63.5,
            'totalStake': 104,
            'averageOdd': 1.74,
            'bestWinStreak': 11,
        },
        'Sir_Chatonne': {
            'profit': 3.78,
            'roi': 3.74,
            'wins': 65,
            'bets': 101,
            'winRate': 64.4,
            'totalStake': 101,
            'averageOdd': 1.61,
            'bestWinStreak': 6,
        },
        'K-Dab': {
            'profit': 8.58,
            'roi': 8.25,
            'wins': 62,
            'bets': 104,
            'winRate': 59.6,
            'totalStake': 104,
            'averageOdd': 1.82,
            'bestWinStreak': 6,
        },
        'M9rgan': {
            'profit': -0.07,
            'roi': -0.07,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.79,
            'bestWinStreak': 6,
        },
        'GOAT#UEBF1WEA': {
            'profit': -8.42,
            'roi': -8.1,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.65,
            'bestWinStreak': 6,
        },
        'Foz': {
            'profit': 13.54,
            'roi': 14.25,
            'wins': 56,
            'bets': 95,
            'winRate': 58.9,
            'totalStake': 95,
            'averageOdd': 1.94,
            'bestWinStreak': 6,
        },
        'CedreLePoulpe': {
            'profit': -7.58,
            'roi': -7.36,
            'wins': 58,
            'bets': 103,
            'winRate': 56.3,
            'totalStake': 103,
            'averageOdd': 1.65,
            'bestWinStreak': 6,
        },
        'Merwi': {
            'profit': -7.5,
            'roi': -7.21,
            'wins': 59,
            'bets': 104,
            'winRate': 56.7,
            'totalStake': 104,
            'averageOdd': 1.64,
            'bestWinStreak': 5,
        },
        'Jean-Porc-Jajo': {
            'profit': 8.67,
            'roi': 9.22,
            'wins': 50,
            'bets': 94,
            'winRate': 53.2,
            'totalStake': 94,
            'averageOdd': 2.05,
            'bestWinStreak': 6,
        },
        'HugBagr': {
            'profit': -12.41,
            'roi': -11.93,
            'wins': 52,
            'bets': 104,
            'winRate': 50,
            'totalStake': 104,
            'averageOdd': 1.76,
            'bestWinStreak': 4,
        },
        'BRANDAO_DOBRAZIL': {
            'profit': 4.22,
            'roi': 4.74,
            'wins': 53,
            'bets': 89,
            'winRate': 59.6,
            'totalStake': 89,
            'averageOdd': 1.76,
            'bestWinStreak': 6,
        },
        'Pascalou_': {
            'profit': -30.67,
            'roi': -37.86,
            'wins': 14,
            'bets': 81,
            'winRate': 17.3,
            'totalStake': 81,
            'averageOdd': 3.6,
            'bestWinStreak': 2,
        },
    },
    'unibet': {
        'Adedadz': {
            'profit': 9.29,
            'roi': 8.93,
            'wins': 69,
            'bets': 104,
            'winRate': 66.3,
            'totalStake': 104,
            'averageOdd': 1.64,
            'bestWinStreak': 7,
        },
        'AlexRougier': {
            'profit': 11.96,
            'roi': 11.5,
            'wins': 66,
            'bets': 104,
            'winRate': 63.5,
            'totalStake': 104,
            'averageOdd': 1.76,
            'bestWinStreak': 11,
        },
        'Sir_Chatonne': {
            'profit': 4.79,
            'roi': 4.74,
            'wins': 65,
            'bets': 101,
            'winRate': 64.4,
            'totalStake': 101,
            'averageOdd': 1.63,
            'bestWinStreak': 6,
        },
        'K-Dab': {
            'profit': 8.92,
            'roi': 8.58,
            'wins': 62,
            'bets': 104,
            'winRate': 59.6,
            'totalStake': 104,
            'averageOdd': 1.82,
            'bestWinStreak': 6,
        },
        'M9rgan': {
            'profit': 0.57,
            'roi': 0.55,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.8,
            'bestWinStreak': 6,
        },
        'GOAT#UEBF1WEA': {
            'profit': -7.49,
            'roi': -7.2,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.66,
            'bestWinStreak': 6,
        },
        'Foz': {
            'profit': 14.66,
            'roi': 15.43,
            'wins': 56,
            'bets': 95,
            'winRate': 58.9,
            'totalStake': 95,
            'averageOdd': 1.96,
            'bestWinStreak': 6,
        },
        'CedreLePoulpe': {
            'profit': -6.86,
            'roi': -6.66,
            'wins': 58,
            'bets': 103,
            'winRate': 56.3,
            'totalStake': 103,
            'averageOdd': 1.66,
            'bestWinStreak': 6,
        },
        'Merwi': {
            'profit': -6.72,
            'roi': -6.46,
            'wins': 59,
            'bets': 104,
            'winRate': 56.7,
            'totalStake': 104,
            'averageOdd': 1.65,
            'bestWinStreak': 5,
        },
        'Jean-Porc-Jajo': {
            'profit': 9.28,
            'roi': 9.87,
            'wins': 50,
            'bets': 94,
            'winRate': 53.2,
            'totalStake': 94,
            'averageOdd': 2.07,
            'bestWinStreak': 6,
        },
        'HugBagr': {
            'profit': -11.62,
            'roi': -11.17,
            'wins': 52,
            'bets': 104,
            'winRate': 50,
            'totalStake': 104,
            'averageOdd': 1.78,
            'bestWinStreak': 4,
        },
        'BRANDAO_DOBRAZIL': {
            'profit': 5.07,
            'roi': 5.7,
            'wins': 53,
            'bets': 89,
            'winRate': 59.6,
            'totalStake': 89,
            'averageOdd': 1.77,
            'bestWinStreak': 6,
        },
        'Pascalou_': {
            'profit': -28.01,
            'roi': -34.58,
            'wins': 14,
            'bets': 81,
            'winRate': 17.3,
            'totalStake': 81,
            'averageOdd': 3.79,
            'bestWinStreak': 2,
        },
    },
    'winamax': {
        'Adedadz': {
            'profit': 8.58,
            'roi': 8.25,
            'wins': 69,
            'bets': 104,
            'winRate': 66.3,
            'totalStake': 104,
            'averageOdd': 1.63,
            'bestWinStreak': 7,
        },
        'AlexRougier': {
            'profit': 10.66,
            'roi': 10.25,
            'wins': 66,
            'bets': 104,
            'winRate': 63.5,
            'totalStake': 104,
            'averageOdd': 1.74,
            'bestWinStreak': 11,
        },
        'Sir_Chatonne': {
            'profit': 3.75,
            'roi': 3.71,
            'wins': 65,
            'bets': 101,
            'winRate': 64.4,
            'totalStake': 101,
            'averageOdd': 1.61,
            'bestWinStreak': 6,
        },
        'K-Dab': {
            'profit': 8.19,
            'roi': 7.87,
            'wins': 62,
            'bets': 104,
            'winRate': 59.6,
            'totalStake': 104,
            'averageOdd': 1.81,
            'bestWinStreak': 6,
        },
        'M9rgan': {
            'profit': -0.57,
            'roi': -0.55,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.78,
            'bestWinStreak': 6,
        },
        'GOAT#UEBF1WEA': {
            'profit': -8.41,
            'roi': -8.09,
            'wins': 58,
            'bets': 104,
            'winRate': 55.8,
            'totalStake': 104,
            'averageOdd': 1.65,
            'bestWinStreak': 6,
        },
        'Foz': {
            'profit': 13.52,
            'roi': 14.23,
            'wins': 56,
            'bets': 95,
            'winRate': 58.9,
            'totalStake': 95,
            'averageOdd': 1.94,
            'bestWinStreak': 6,
        },
        'CedreLePoulpe': {
            'profit': -7.62,
            'roi': -7.4,
            'wins': 58,
            'bets': 103,
            'winRate': 56.3,
            'totalStake': 103,
            'averageOdd': 1.64,
            'bestWinStreak': 6,
        },
        'Merwi': {
            'profit': -7.37,
            'roi': -7.09,
            'wins': 59,
            'bets': 104,
            'winRate': 56.7,
            'totalStake': 104,
            'averageOdd': 1.64,
            'bestWinStreak': 5,
        },
        'Jean-Porc-Jajo': {
            'profit': 8.06,
            'roi': 8.57,
            'wins': 50,
            'bets': 94,
            'winRate': 53.2,
            'totalStake': 94,
            'averageOdd': 2.04,
            'bestWinStreak': 6,
        },
        'HugBagr': {
            'profit': -13.2,
            'roi': -12.69,
            'wins': 52,
            'bets': 104,
            'winRate': 50,
            'totalStake': 104,
            'averageOdd': 1.75,
            'bestWinStreak': 4,
        },
        'BRANDAO_DOBRAZIL': {
            'profit': 3.96,
            'roi': 4.45,
            'wins': 53,
            'bets': 89,
            'winRate': 59.6,
            'totalStake': 89,
            'averageOdd': 1.75,
            'bestWinStreak': 6,
        },
        'Pascalou_': {
            'profit': -31.44,
            'roi': -38.81,
            'wins': 14,
            'bets': 81,
            'winRate': 17.3,
            'totalStake': 81,
            'averageOdd': 3.54,
            'bestWinStreak': 2,
        },
    },
}
